apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  resources:
    requests:
      storage: "2Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: nginx-pvc
            readOnly: false
      initContainers:
        - name: node-builder
          image: node:12.16.3-slim
          command: ["bash", "-c", "apt-get update && apt-get install -y git && git clone https://github.com/pablo-moreno/pablo-moreno.github.io.git web && cd web && npm i && npm run build && cp -r dist/* /code"]
          volumeMounts:
            - name: nginx-volume
              mountPath: /code
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: nginx-volume
            mountPath: /usr/share/nginx/html/
        ports:
        - containerPort: 80
